[command.download_github_artifact]
usage = "<user/repo> <artifact_filename_regex> <output_path>"
body = { no_tty_log = [ 
  { echo = [ "Downloading artifact from github ", 1] },
  # Download latest release information
  { set = [
    "releaseinfo",
    { curl = [["https://api.github.com/repos/", 1, "/releases/latest"]] }
  ] },
  # Get a matching url, make there is atleast 1 url that matches
  { set = [ "nonce", { jsonquote = { randomstr = "42" } } ] },
  { set = [ "url", { firstline = { jq = [
    ['([.assets[]|select(.name|test(', { jsonquote = 2 }, ')).url]+[', { get = "nonce" }, '])[0]'], # pattern
    { get = "releaseinfo" }
  ] } } ] },
  { assert_neq = [ { get = "nonce" }, { get = "url" }, "No suitable github release found" ] },
  { echo = [ "Found URL ", { get = "url" } ] },
  # Download the payload
  { curl = [ "-H", "Accept: application/octet-stream", { jsonunquote = { get = "url" } }, "--output", 3] },
  { echo = [ "Finished downloading to ", 3 ] },
] }

[command.jq]
usage = "<pattern> <json>"
body = [
  # Download Jaq, the rust jq clone
  # TODO: mkdirp, temp dir and temp file names
  { if_not_exists = "jaq", then = [
    { echo = [ "First call to jq, downloading jaq..." ] },
    { curl = [ "-o", "./jaq", [ 
      "https://github.com/01mf02/jaq/releases/latest/download/jaq-",
      { get = "arch" },
      "-unknown-linux-musl"
    ] ] },
    { echo = [ "Jaq binary cached!" ] },
  ] },
  { sh = [ "printf -- '%s' ", { shquote = [ 2 ] }, ' | jaq -- ', { shquote = [ 1 ] }, " | tee" ] }
]

[command.sh]
usage = "<shell input>"
body = { exec = [{ get="shell_path" }, "-c", [{}]] }

[command.curl]
usage = "<url> [<extra curl args>]*"
body = { exec = ["curl", "-L#fs", "--proto", "=https", "--tlsv1.2", "--create-dirs", {}] }

