---
- become: yes
  become_method: sudo
  vars:
    agneau_server_uname: agneau
    agneau_user_pwd: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              35373964616465366334366634636330306539663531323936633131336266383864396439373836
              6236303539363136343134616231643433376639326432390a383861363766396162633839323862
              30623361393237386364663863363638323038613063643932383232623033393239613838326535
              6135613036643337370a346633323137643433653862613735353864333134313662636131643936
              30343835396636346666313166383730333538303337386365306337333364336331
  tasks:
  - name: Install packages
    apt:
      update_cache: yes
      upgrade: full
      pkg:
      - ufw
      - unattended-upgrades
      - mosh
      - curl
      - socat

  - name: Set up networking
    block:
    # TODO: make sure you can bind to SSH ports with current running ansible instance
  
    - name: Setup alternate SSH port
      lineinfile:
        dest: '/etc/ssh/sshd_config'
        regexp: '^Port'
        line: 'Port 79'
    - name: Setup SELinux for alternate SSH port
      seport:
        ports: '79'
        proto: 'tcp'
        setype: 'ssh_port_t'
        state: present
    - name: Delete all firewall rules
      ufw:
        state: reset
    - name: Enable firewall
      ufw:
        state: enabled
        policy: allow
    - name: Manually disable privileged ports through firewall
      # Allowed ports are: 22 (fake SSH), 68 (DHCP/BOOTP), 79 (actual SSH),
      # 80 (cleartext HTTP), 443 (TLS+HTTP, QUIC+HTTP)
      tasks:
      - ufw:
          comment: 'Deny low ports between standard SSH port and BOOTP/DHCP'
          rule: deny
          port: '23:67'
      - ufw:
          comment: 'Deny low ports between BOOTP/DHCP and actual SSH port'
          rule: deny
          port: '69:78'
      - ufw:
          comment: 'Deny low ports between HTTP and HTTPS'
          rule: deny
          port: '81:442'
      - ufw:
          comment: 'Deny low ports between HTTPS and unprivileged port start'
          rule: deny
          port: '444:1023'
      - ufw:
          comment: 'Rate limit disguised SSH port'
          rule: limit
          port: '79'

    # This isn't as big of a risk because we have UFW :>
    - name: Allow binding to low ports
      sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: '22'
        sysctl_set: yes

    - name: Setup unattended upgrades
      service:
        name: unattended-upgrades
        enabled: yes
        state: started

    - name: Disable SSH root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    # TODO: add custom ssh key
    # TODO: add ssh login alerts
    - name: Remove root login
      user:
        name: root
        password_lock: yes
        password: !
        shell: /sbin/nologin
        uid: 1
        append: true
        create_home: false
        home: /root

    # TODO: add new user, add them to sudoers
    - name: 'Add user {{ agneau_server_uname }}' 
      user:
        name: '{{ agneau_server_uname }}'
        append: true
        uid: 1000
        groups: sudo
        password: '{{ agneau_user_pwd }}'
      
    - name: Restart SSHd
      systemd:
        name: sshd
        state: restarted

  
