---
- become: yes
  hosts: pre_security
  become_method: sudo
  vars_files:
    - 'config.yml'
  tasks:
  - name: Start firewall setup (disable ufw)
    ufw: {state: 'disabled', policy: 'deny'}

  - name: Manually enable privileged ports through firewall
    ufw:
      rule: "{{item[0]}}"
      port: "{{item[1]}}"
      proto: "{{item[2]}}"
      comment: "{{item[3]}}"
    loop:
      # Allowed ports <1024 
    - ["allow", "22", "any", "Allow fake SSH"]
    - ["allow", "68", "any", "Allow DHCP"] # Or BOOTP? idk what that is
    - ["allow", "80", "any", "Allow HTTP"]
    - ["allow", "443", "any", "Allow HTTPS"] # and QUIC

      # Unprivileged ports
    - ["allow", "1024:65535", "tcp", "Allow unprivileged ports with TCP"]
    - ["allow", "1024:65535", "udp", "Allow unprivileged ports with UDP"]

      # SSH ports
    - ["allow", "{{ new_ssh_port }}", "any", "Allow actual/hidden SSH port"]
    - ["limit", "{{ new_ssh_port }}", "tcp", "Rate limit SSH port"]

  - name: 'Finish firewall setup (enable ufw)'
    ufw: {state: 'enabled', policy: 'deny'}

  # This isn't as big of a risk because we have UFW :>
  - name: Allow binding to low ports
    sysctl:
      name: net.ipv4.ip_unprivileged_port_start
      # Lowest port we need to bind to is 22
      value: '22'
      sysctl_set: yes

