---
- become: yes
  hosts: pre_security
  become_method: sudo
  vars_files:
    - 'config.yml'
  tasks:
  - name: Start firewall setup (disable ufw)
    ufw: {state: 'disabled', policy: 'deny'}
  - name: Delete all firewall rules
    ufw: {state: 'reset'}

  - name: Manually enable privileged ports through firewall
    # Allowed ports are: 22 (fake SSH), 68 (DHCP/BOOTP), ?? (actual SSH),
    # 80 (cleartext HTTP), 443 (TLS+HTTP, QUIC+HTTP)
    block:
    - name: 'Allow fake SSH'
      ufw: {rule: 'allow', port: '22', comment: 'Allow fake SSH'}
    - name: 'Allow DHCP'
      ufw: {rule: 'allow', port: '68', comment: 'Allow DHCP'}
    - name: 'Allow HTTP'
      ufw: {rule: 'allow', port: '80', comment: 'Allow HTTP'}
    - name: 'Allow actual SSH port'
      ufw: {rule: 'allow', port: '{{ new_ssh_port }}', comment: 'Allow actual SSH port'}
    - name: 'Allow HTTPS'
      ufw: {rule: 'allow', port: '443', comment: 'Allow HTTPS'}
    - name: 'Allow unprivileged ports, tcp'
      ufw: {rule: 'allow', port: '1024:65535', proto: 'tcp', comment: 'Allow unprivileged ports, tcp'}
    - name: 'Allow unprivileged ports, udp'
      ufw: {rule: 'allow', port: '1024:65535', proto: 'udp', comment: 'Allow unprivileged ports, udp'}
    - name: 'Rate limit SSH port'
      ufw: {rule: 'limit', port: '{{ new_ssh_port }}', proto: 'tcp', comment: 'Rate limit SSH port'}

  - name: 'Finish firewall setup (enable ufw)'
    ufw: {state: 'enabled', policy: 'deny'}

  # This isn't as big of a risk because we have UFW :>
  - name: Allow binding to low ports
    sysctl:
      name: net.ipv4.ip_unprivileged_port_start
      # Lowest port we need to bind to is 22
      value: '22'
      sysctl_set: yes

