---
- become: yes
  hosts: pre_security
  become_method: sudo
  vars_files:
    - 'config.yml'
  tasks:
  - name: "Add sudo group to sudoers"
    community.general.sudoers:
      group: sudo
      commands: ALL
      state: present
      name: bigguys
      nopassword: no

  - name: Remove root login
    user:
      name: root
      password_lock: yes
      password: !
      shell: /sbin/nologin
      append: true
      uid: 0
      groups: root
      create_home: false
      home: /root

  - name: "Add user {{ new_user_name }}"
    user:
      name: "{{ new_user_name }}"
      append: true
      uid: 1000
      groups: sudo
      shell: /usr/bin/bash
      password: "{{ new_user_pwd | string | password_hash(salt=pwd_hash_salt) }}"
      home: '/home/{{ new_user_name }}'

  - name: 'Create secure directory'
    file:
      path: '/home/{{ new_user_name }}/secure'
      owner: root
      mode: '700'
      state: directory

  - name: Add SSH pubkey for user
    authorized_key:
      user: "{{ new_user_name }}"
      state: present
      key: "{{ new_user_ssh_pubkey }}"

