---
- become: yes
  hosts: pre_security
  become_method: sudo
  vars_files:
    - '../config.yml'
  vars:
    cron_timings:
      # MAYBE: consider changing cron special time to regular time 
      # Display name, cron special time name, filesystem name
    - [yearly, yearly, Yearly]
    - [monthly, monthly, Monthly]
    - [daily, daily, Daily]
    - [hourly, hourly, Hourly]
  tasks:
  # Cron filesystem
  - name: 'beancron: Create folders - general folders'
    file:
      path: '{{ item[0] }}'
      state: directory
      owner: '{{ item[1] }}'
      group: '{{ item[1] }}'
      mode: '{{ item[2] }}'
    loop:
    - ["/home/{{ new_user_name }}/Logs/Cron", "{{ new_user_name }}", "700"]
    - ["/home/{{ new_user_name }}/Crons", "{{ new_user_name }}", "700"]
    - ["/home/{{ new_user_name }}/secure/Logs/Cron", "root", "700"]
    - ["/home/{{ new_user_name }}/secure/Crons", "root", "700"]

  - name: 'beancron: Create folders - unprivileged cronjob folder'
    loop: "{{ cron_timings }}"
    file:
      path: '/home/{{ new_user_name }}/Crons/{{ item[2] }}'
      state: directory
      owner: "{{ new_user_name }}"
      group: "{{ new_user_name }}"
      mode: '700'

  - name: 'beancron: Create folders - secure cronjob folder'
    loop: "{{ cron_timings }}"
    file:
      path: '/home/{{ new_user_name }}/secure/Crons/{{ item[2] }}'
      state: directory
      owner: root
      group: root
      mode: '700'

  - name: 'beancron: Create cronjob runner scripts'
    loop: "{{ cron_timings }}"
    vars: {cron_scripts_path: '{{ item[2] }}'}
    template:
      dest: '/home/{{ new_user_name }}/secure/Crons/{{ item[2] }}/start_all_jobs.py'
      src: './beancron_start_cron_jobs.py'
      owner: 'root'
      group: 'root'
      mode: '700'

  - name: 'beancron: Create crontab jobs to run their respective runner script'
    loop: "{{ cron_timings }}"
    cron:
      name: '{{ item[0] }} beancron jobs'
      special_time: '{{ item[1] }}'
      job: '/home/{{ new_user_name }}/secure/Crons/{{ item[2] }}/start_all_jobs.py'

  # Restart cron
  - name: 'beancron: Restart cron'
    systemd: {state: restarted, enabled: yes, masked: no, unit: cron}

  # TODO: planning for services:
  # 1. secure cronscript for thor-lite
  # 2. adapt beanbag to use JUST for the scripts :D and just run just commands. We can't use s6 cuz it needs a compilation, and a C compilation at that...
  # 3. fd structure:
  #    home
  #     X/
  #       <...>
  #     Services/
  #       Service 1/
  #         bean.toml
  #         Justfile
  #         <...regular service files/links...>
  #       Service 2/
  #         bean.zip
  #         <...regular service files/links...>
  #     Beanbag/
  #       datafiles/
  #         Service 1/
  #           <...>
  #       services/
  #         Service 1/
  #           bean.toml
  #           Justfile
  #         Service 2_v1.0.1.zip
  #     Logs/
  #       <...logs...>
  #     Crons/
  #       Monthly/
  #       Daily/
  #         backup.toml
  #       Hourly/
  #     secure/
  #       ...

