---
- become: yes
  hosts: pre_security
  become_method: sudo
  vars_files:
    - '../config.yml'
  vars:
    thor_lite_folder: '/home/{{ new_user_name }}/secure/thor-lite'
  tasks:
  - name: 'Check if Thor lite is already downloaded'
    stat:
      dest: '{{ thor_lite_folder }}'
    register: thor_lite_folder_stat

  - name: 'Make Thor directory'
    when: 'not thor_lite_folder_stat.stat.exists'
    file:
      dest: '{{ thor_lite_folder }}'
      owner: 'root'
      group: 'root'
      mode: '700'
      state: directory

  - name: 'Download Thor lite'
    when: 'not thor_lite_folder_stat.stat.exists'
    unarchive:
      src: '{{ thor_download_url }}'
      remote_src: yes
      dest: '{{ thor_lite_folder }}'
      owner: 'root'
      group: 'root'
      mode: '700'

  - name: 'Update Thor lite license'
    copy:
      src: '../thor_license_file.lic'
      dest: '{{ thor_lite_folder }}/{{ thor_license_file_name }}'
      mode: '500'

  # - name: 'Update Thor lite'
  #   command: '{{ thor_lite_folder }}/thor-lite-util upgrade'

  - name: 'Add autoupdate & scan cron-job'
    copy:
      dest: '/home/{{ new_user_name }}/secure/Crons/Daily/thor_lite_update_and_daily_scan.sh'
      mode: '700'
      owner: 'root'
      group: 'root'
      content: "#!/usr/bin/env bash\nset -euxo pipefail\n'{{ thor_lite_folder }}/thor-lite-util' upgrade\n'{{ thor_lite_folder }}/thor-lite-linux-64' -c 60 -e '/home/{{ new_user_name }}/secure/Logs/Security'"

