---
- become: yes
  hosts: pre_security
  become_method: sudo
  vars_files:
    - '../config.yml'
  vars:
    ssh_alert_file_path: '/home/{{ new_user_name }}/secure/ssh_login_alert.sh'
    ssh_alert_config_line: "session optional pam_exec.so {{ ssh_alert_file_path }}"
    ssh_alert_file_content: '#!/usr/bin/env bash'
  tasks:
  - name: 'Install mosh locales'
    shell: 'locale-gen en_US.UTF-8'

  - name: 'Check if SSH alerts are set up'
    # credit: https://stackoverflow.com/questions/29075287
    lineinfile:
      state: absent
      path: "/etc/pam.d/sshd"
      search_string: "{{ ssh_alert_config_line }}"
    check_mode: yes
    changed_when: no
    register: ssh_alert_line_check

  - name: 'Create empty SSH alert script'
    when: ssh_alert_line_check.found == 0
    copy:
      dest: "{{ ssh_alert_file_path }}"
      content: '{{ ssh_alert_file_content }}'
      owner: root
      group: root
      mode: '700'
      force: no

  - name: 'Set up ssh alert in PAM configs'
    when: ssh_alert_line_check.found == 0
    lineinfile:
      state: present
      path: "/etc/pam.d/sshd"
      line: '{{ssh_alert_config_line}}'

  - name: Alter selinux settings for SSH port
    when: update_selinux
    block:
    - name: Setup SELinux for alternate SSH port
      seport:
        ports: '{{ new_ssh_port }}'
        proto: 'tcp'
        setype: 'ssh_port_t'
        state: present

    - name: Remove SELinux 22 port for SSH
      seport:
        ports: 22
        protocol: tcp
        setype: ssh_port_t
        state: absent
        local: true

  - name: Harden and setup /etc/ssh/sshd_config
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^{{ item[0] }}"
      line: "{{ item[0] }} {{ item[1] }}"
    loop:
    # Port setup (important)
    - ['Port', "{{ new_ssh_port }}"]
    # Login hardening
    - ['PermitRootLogin', 'NO'] # Disable SSH root login
    - ['PasswordAuthentication', 'NO'] # Disable SSH password-based login
    - ['KbdInteractiveAuthentication', 'NO'] # Disable keyboard-interactive login
    - ['UsePAM', 'YES'] # Enable PAM login

    # Protocol
    - ['X11Forwarding', 'NO'] # Disable X11 forwarding
    - ['MaxAuthTries', '3'] # Setup max SSH auth tries
    - ['MaxSessions', '2'] # Setup max SSH sessions
    - ['ClientAliveCountMax', '2'] # Setup SSH max client alives
    - ['TCPKeepAlive', 'NO'] # Setup SSH keepalive method
    - ['AllowAgentForwarding', 'NO'] # Setup SSH agent forwarding
    - ['AllowTcpForwarding', 'NO'] # Setup SSH TCP forwarding

    # Etc
    - ['LogLevel', 'VERBOSE'] # Setup verbose SSH logging
    - ['Banner', '/etc/motd'] # Setup SSH login banner to scare ppl OOooOoOOooOo

  - name: Restart SSHd
    systemd:
      name: sshd
      state: restarted

  # TODO: add ssh login alerts
